import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Narra Suryakoushik Reddy | AI and DevOps Engineering Student",
  description: "AI Engineer and DevOps enthusiast specializing in intelligent automation and machine learning systems. Building production-grade AI solutions with expertise in Python, TensorFlow, Docker, and cloud technologies.",
  keywords: [
    "artificial-intelligence",
    "machine-learning",
    "devops",
    "automation",
    "python",
    "tensorflow",
    "keras",
    "scikit-learn",
    "nlp",
    "opencv",
    "docker",
    "kubernetes",
    "linux",
    "git",
    "github",
    "ai-engineer",
    "data-science",
    "deep-learning",
    "neural-networks",
    "aws",
    "cloud-computing",
    "api-development",
    "flask",
    "n8n",
    "workflow-automation",
    "portfolio",
    "student",
    "computer-science",
    "mca",
    "nextjs",
    "react",
    "typescript",
    "javascript",
  ] as Array<string>,
  authors: {
    name: "Narra Suryakoushik Reddy",
    url: "https://github.com/KoushikScripts",
  },
} as const;
